### ISSUE TITLE
CGPM 1st meeting missing English translation of sanctions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/cgpm-resolutions#4]
https://www.bipm.org/en/CGPM/db/1/1/

English:
<img width="789" alt="Screen Shot 2020-09-06 at 2 49 51 PM" src="https://user-images.githubusercontent.com/11865/92319945-39715500-f050-11ea-96a4-c4e7c67d96e2.png">

French:
<img width="783" alt="Screen Shot 2020-09-06 at 2 50 26 PM" src="https://user-images.githubusercontent.com/11865/92319957-4d1cbb80-f050-11ea-9c2e-04dd7df8f4f6.png">

Translated:
A. Regarding international prototypes:
1. The Prototype of the meter chosen by the CIPM. This prototype, at the temperature of melting ice, shall henceforth represent the metric unit of length.
2. The Prototype of the kilogram adopted by the CIPM. This prototype shall henceforth be considered as the unit of mass.
3. The hydrogen thermometer centigrade scale in terms of which the equations of the prototype Metres have been established.

B. Regarding national prototypes:
1. Meters of platinum iridium, the equations of which, with respect to the international Prototype, are contained within the limit of 0.01 millimeter, with a probable error not exceeding ± 0.0002 millimeter.
2. Kilograms of platinum iridium, the equations of which are contained within the limit of 1 milligram, with a probable error not exceeding ± 0.005 milligram.

C. Regarding the equations of the national prototypes:
The equations of the national prototypes, as determined at the International Bureau, under the direction of the CIPM, and recorded in the Report of this Committee and on the certificates accompanying these prototypes.

**Comment by anermina** [comment]
Added in #17 . Closing.
